set(CTEST_SOURCE_DIRECTORY "/source")
set(CTEST_BINARY_DIRECTORY "/binary/@BUILD_CONFIG@")

if(CLEAN_BUILD)
  ctest_empty_binary_directory(${CTEST_BINARY_DIRECTORY})
endif()

site_name(CTEST_SITE)
set(CTEST_BUILD_NAME "$ENV{BUILD_NAME}")

set(CTEST_CUSTOM_MAXIMUM_NUMBER_OF_WARNINGS 1000)
set(CTEST_CMAKE_GENERATOR "Ninja")

set(CTEST_COVERAGE_COMMAND "$ENV{CTEST_COVERAGE_COMMAND}")
set(CTEST_MEMORYCHECK_COMMAND "$ENV{CTEST_MEMORYCHECK_COMMAND}")
set(CTEST_MEMORYCHECK_TYPE "$ENV{CTEST_MEMORYCHECK_TYPE}")

ctest_start("@BUILD_MODEL@")
ctest_configure(@CONFIGURE_ARGS@)
ctest_build()

if(RUN_TESTS)
  ctest_test(@TEST_ARGS@)
  if(CTEST_COVERAGE_COMMAND)
    ctest_coverage()
  endif()
  if(CTEST_MEMORYCHECK_COMMAND OR CTEST_MEMORYCHECK_TYPE)
    ctest_memcheck(@TEST_ARGS@)
  endif()
endif()

ctest_submit()
